name: Build Flutter Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # لتشغيل يدوي

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      APP_NAME: "Nwara Store"  # ضع اسم التطبيق هنا

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.5" # ضع نسخة Flutter المناسبة

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Change Windows App Name
        shell: pwsh
        run: |
          $cmakePath = "windows\runner\CMakeLists.txt"
          if (Test-Path $cmakePath) {
            $content = Get-Content $cmakePath
            $content = $content -replace 'set\(PROJECT_NAME ".*"\)', "set(PROJECT_NAME '$env:APP_NAME')"
            Set-Content $cmakePath $content
            Write-Host "Project name updated successfully"
          } else {
            Write-Host "CMakeLists.txt not found, skipping app name change"
          }

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows Release
        run: flutter build windows --release

      - name: Verify Release folder
        shell: pwsh
        run: |
          $releasePath = "build\windows\runner\Release\x64"
          if (Test-Path $releasePath) {
            Write-Host "Release folder exists. Listing files:"
            Get-ChildItem -Path $releasePath -Recurse
          } else {
            Write-Host "Release folder does not exist. Build failed or host is not Windows."
            exit 1
          }

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows/runner/Release/x64/**
